[workspace]
members = [
    "bindgen",
    "fixtures",
]

resolver = "2"

[workspace.dependencies]
uniffi = { git = "https://github.com/NordSecurity/uniffi-rs.git", tag="v0.3.1+v0.25.0" }
uniffi_bindgen = { git = "https://github.com/NordSecurity/uniffi-rs.git", tag="v0.3.1+v0.25.0" }
