/* This file was generated by uniffi-bindgen-cpp. */

#include <bit>
#include <string>

#include "{{ ci.namespace() }}.hpp"

{{ type_helper_code }}

{% include "helpers.cpp" %}
{% include "rust_buf_tmpl.cpp" %}

{%- for func in ci.function_definitions() %}
{% include "fn_tmpl.cpp" -%}
{% endfor %}

{% import "macros.cpp" as macros %}
