template <typename T> struct HandleMap {
    HandleMap() = default;

    std::shared_ptr<T> at(uint64_t handle) {
        std::lock_guard<std::mutex> guard(this->mutex);

        return this->map.at(handle);
    }

    uint64_t insert(std::shared_ptr<T> impl) {
        std::lock_guard<std::mutex> guard(this->mutex);

        return this->insert_locked(impl);
    }

    uint64_t clone(uint64_t handle) {
        std::lock_guard<std::mutex> guard(this->mutex);

        return this->insert_locked(this->map.at(handle));
    }

    void erase(uint64_t handle) {
        // We store the object here to avoid re-entrant locking
        std::shared_ptr<T> cleanup;
        {
            std::lock_guard<std::mutex> guard(this->mutex);
            auto it = this->map.find(handle);
            if (it != this->map.end()) {
                cleanup = it->second;
                this->map.erase(it);
            }
        }
    }

    private:
        HandleMap(const HandleMap<T> &) = delete;
        HandleMap(HandleMap<T> &&) = delete;

        HandleMap<T> &operator=(const HandleMap<T> &) = delete;
        HandleMap<T> &operator=(HandleMap<T> &&) = delete;

        std::mutex mutex;
        /// Rust handles are generated by leaking a raw pointer.
        /// Foreign handles are generated with a handle map that only generates odd values.
        /// * 0 is an invalid value.
        /// * The lowest bit will always be set for foreign handles and never set for Rust ones
        uint64_t cur_handle = 1;
        std::map<uint64_t, std::shared_ptr<T>> map;


        uint64_t insert_locked(std::shared_ptr<T> impl) {
            auto handle = this->cur_handle;

            this->map.insert({ handle, impl });
            this->cur_handle += 2;

            return handle;
        }
};
